export const companies = [
  {
    name: "Company 1",
    id: 1,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 1 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "3 June 2022 - 5 June 2030",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "3 June 2022 - 5 June 2030",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "3 June 2022 - 5 June 2030",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "3 June 2022 - 5 June 2030",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "3 June 2022 - 5 June 2030",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "3 June 2022 - 5 June 2030",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 2",
    id: 2,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 2 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 3",
    id: 3,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 3 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 4",
    id: 4,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 4 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 5",
    id: 5,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 5 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 6",
    id: 6,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 6 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 7",
    id: 7,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 7 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 8",
    id: 8,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 8 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 9",
    id: 9,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 9 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 10",
    id: 10,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 10 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 11",
    id: 11,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 11 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 12",
    id: 12,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 12 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 13",
    id: 13,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 13 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 14",
    id: 14,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 14 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 15",
    id: 15,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 15 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 16",
    id: 16,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 16 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 17",
    id: 17,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 17 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 18",
    id: 18,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 18 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 19",
    id: 19,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 19 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
  {
    name: "Company 20",
    id: 20,
    logo: "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png",
    description: "Company 20 description",
    website: "https://www.google.com",
    location: "San Francisco, CA",
    entries: [
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
      {
        billingLocation: "Bangalore",
        entityName: "LUCF",
        entityCode: "LUCF",
        mslaValidThrough: "12/12/2021",
        fileSharing: "Yes",
      },
    ],
  },
];

export const ClientTabs = ["ENTRIES", "INVOICE CODES", "USERS"];
